'use client';
import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.scss';
import './style.css';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="fr">
        {/* <Head>
            <title>Dr Cheikh Gueye</title>
        </Head> */}
        {/* <AnimatePresence mode="wait" initial={false}> */}
        <body>
          <div className="flex flex-1 flex-col">
            <Navbar />
            {children}
          </div>
          <Footer />
        </body>
      {/* </AnimatePresence> */}
    </html>
  )
}
