'use client';
import './globals.scss'
import { motion,AnimatePresence } from 'framer-motion'
import Navbar from './components/Navbar';
import Head from "next/head"
import Footer from './components/Footer';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="fr">
        {/* <Head>
            <title>Dr Cheikh Gueye</title>
        </Head> */}
        {/* <AnimatePresence mode="wait" initial={false}> */}
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      {/* </AnimatePresence> */}
    </html>
  )
}
