'use client';
import './globals.scss'
import { motion,AnimatePresence } from 'framer-motion'
import Navbar from './components/Navbar';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="fr">

        {/* <AnimatePresence mode="wait" initial={false}> */}
        <body>
          <Navbar />
          {children}
        </body>
      {/* </AnimatePresence> */}
    </html>
  )
}
